### ISSUE TITLE
GA ID 충돌에 의한 잘못된 정보 수집 및 통계 오류

### ISSUE THREAD

**Issue by JaeSeoKim** [Seongwon97/Seongwon97.github.io#3]
현재 저의 블로그소스를 활용하여 운영중이신 것 같으신데, Google analystics ID가 충돌 되어 저의 GA에서 잘못된 정보가 수집되어 적절한 사용자 통계를 보는 것에 문제가 발생하고 있습니다.

혹시 해당 부분에 대해서 해결 가능할까요?
그리고 저의 소스를 활용해서 사용하고 있다는 부분도 표기해주시면 감사하겠습니다.

**Comment by Seongwon97** [comment]
헉..죄송합니다..
Google analystics ID를 변경해야지 변경해야지했는데..잊고 있었네요😭
바로 변경하였습니다!

재서님 소스를 활용하고 있다는 점도 README를 만들며 표기해뒀습니다!!

만들어두신 템플릿 잘 사용하고 있습니다
템플릿 사용 허락해주셔서 다시 한번 감사드립니다🙇🏻‍♂️

**Comment by JaeSeoKim** [comment]
아 그리고 사실 현재 블로그 템플릿이 만들어진지 오래되어서 다른 스택으로 처음부터 다시 제작을 진행하고 있는데, 혹시 개선 되었으면 하는 부분이 있을까요?

**Comment by Seongwon97** [comment]
이전에 사용하던 개발블로그들의 디자인이 마음에 안들어 여러 템플릿을 찾아봤으나 디자인적으로도 제공하는 기능적으로도 모두 만족하며 사용하고 있습니다😁
다만 한가지 개선되면 좋겠는 부분이 있다면 게시글 태그들을 메인 페이지에서 한번에 찾아보기 어렵다는 점을 느꼈습니다. 
아래의 사진은 Velog나 다른 Git블로그의 캡쳐본인데 사진과 같이 태그의 목록을 한 눈에 몰아볼 수 있으면 더 좋을 것 같다는 생각이듭니다!

![image](https://user-images.githubusercontent.com/57744251/188479189-6b7ec43a-edbd-470d-b2d3-8dba8aefe026.png)

![image](https://user-images.githubusercontent.com/57744251/188479292-d0befd07-390b-48a4-bcb2-0cbdc5d84028.png)
